### ISSUE TITLE
Black background color on dismiss transition (Objective-C only)

### ISSUE THREAD

**Issue by slxl** [andreamazz/BubbleTransition#12]
```
func animationControllerForDismissedController(dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? {
    transition.transitionMode = .Dismiss
    transition.startingPoint = transitionButton.center
    transition.bubbleColor = transitionButton.backgroundColor!
    return transition
}
```

![ios simulator screen shot 25 2015 19 40 51](https://cloud.githubusercontent.com/assets/3089985/9468045/edf466c2-4b58-11e5-8310-ff4b5a03c35c.png)

Demo project, tested on simulator iOS8.3/iOS8.4 and on iPhone 5s iOS8.4

**Comment by andreamazz** [comment]
Tested now, it's working fine. I did a fresh clone also, just to be sure. 
Which version of Xcode are you using?

**Comment by slxl** [comment]
Version 6.4 (6E35b)

**Comment by andreamazz** [comment]
Yup, same version here, no issues.

**Comment by slxl** [comment]
What environment (iOS version, device/simulator) do you use?

**Comment by andreamazz** [comment]
8.4 on an iPhone 5s as you suggested above.

**Comment by slxl** [comment]
looks like I found, problem was with a setting for segue presentation (full screen instead of default in project), pardon, my fault

**Comment by andreamazz** [comment]
No problem :+1:

**Comment by slxl** [comment]
thanks for tool!

**Comment by andreamazz** [comment]
:+1:

**Comment by slxl** [comment]
@andreamazz problem still persists (but in my project only), looks like its something similar to what google returns for "dismiss modal view controller black screen" request, still looking for solution :/

all presentation settings and stuff are (i hope) identical, the only significant difference is that im using your BubbleTransition.swift in objective-c project. But I think that shouldnt be a problem

**Comment by andreamazz** [comment]
Can you share the code or reproduce part of it in a stand alone project? I'll be happy to take a look at it.

**Comment by slxl** [comment]
Will try tmrw, thanks!

**Comment by slxl** [comment]
ty
-=ı˜ ¿

**Comment by peskish** [comment]
I found solution here:
http://www.raywenderlich.com/forums/viewtopic.php?f=2&t=18661

Add this code in prepareForSegue:

```
UIViewController *controller = segue.destinationViewController;

if (SYSTEM_VERSION_LESS_THAN(@"8.0")) {
} else {
    controller.modalPresentationStyle = UIModalPresentationOverCurrentContext;

}
```

**Comment by slxl** [comment]
@andreamazz Despite being slowpoke, but I'm responsible also :)

https://dl.dropboxusercontent.com/u/18509214/TransitionTest.zip

here is a template project with a same structure as mine original. Would be great if you' have a look whats wrong there. Thanks! )

**Comment by slxl** [comment]
@andreamazz had a time to look?

**Comment by andreamazz** [comment]
Not yet, sorry, I'll get around it this weekend.

**Comment by slxl** [comment]
@andreamazz appreciate this, thanks! I tried few approaches already, we could discuss in skype if you want (id: slxl.ru)

**Comment by andreamazz** [comment]
Well, I'm confused. 
This is the view hierarchy in the sample:
<img width="183" alt="screen shot 2015-09-27 at 19 15 27" src="https://cloud.githubusercontent.com/assets/570797/10124098/2e93bafe-654c-11e5-9fbf-7409406e95d6.png">

You can see the starting view. 
This is the hierarchy of your sample:

<img width="341" alt="screen shot 2015-09-27 at 19 14 52" src="https://cloud.githubusercontent.com/assets/570797/10124101/42218452-654c-11e5-8dde-fa8d4e476274.png">

The starting view is not in the hierarchy, that's why you see a black screen during the transition. 
Can't figure out why...

**Comment by andreamazz** [comment]
Ok, I started a new project, dropped in the animation, and I have the same issue. wth...

**Comment by andreamazz** [comment]
The same sample written in Swift works fine. Awesome.

**Comment by andreamazz** [comment]
Objective-C sample: http://d.pr/f/1fsLx  

Swift sample: http://d.pr/f/1aNFW

**Comment by slxl** [comment]
@andreamazz good news everyone!

somehow in both (yours and mine) projects there was 

```
controller.modalTransitionStyle = UIModalPresentationCustom; // incorrect
```

instead of

```
controller.modalPresentationStyle = UIModalPresentationCustom; // correct
```

thanks to apple developer's support )

**Comment by andreamazz** [comment]
Sneaky! Glad that this wasn't related to the lib itself.  
Thanks for solving the mystery @slxl :+1:  

Cheers

**Comment by slxl** [comment]
i'd say, glad it wasn't related to Obj-C :)

**Comment by andreamazz** [comment]
That would have been awkward :grimacing:

**Comment by alicanbatur** [comment]
This fixed for me, using 
controller.modalPresentationStyle = UIModalPresentationCustom;
instead of
controller.modalTransitionStyle = UIModalPresentationCustom; // incorrect

fyi.
(I'm on a objc project btw.)
