### ISSUE TITLE
Objective-C

### ISSUE THREAD

**Issue by 99centsappdevelopment** [andreamazz/BubbleTransition#13]
Are you considering uploading Objective-C code of this transition?

Looks fantastic, by the way!

**Comment by andreamazz** [comment]
Hi @99centsappdevelopment 
No, since Swift and Objective-C work great together there's no need for me to write this in Objective-C too. You can find an Objective-C implementation in [this gist](https://gist.github.com/andreamazz/9b0d6c7db065555ec0d7)
