### ISSUE TITLE
Transition lag? 

### ISSUE THREAD

**Issue by acegreen** [andreamazz/BubbleTransition#14]
Hello @andreamazz ,

First of thanks for the great work. Library works awesome. 

I'm not sure if my problem is directly linked to bubbleTransition, but I'm noticing a lag on the FIRST button press. From there on after, its smooth as butter.

Note: The startingPoint is incorrect because it appears somewhere on the top though I don't think its CGPointZero but a little under the navigation bar and centered horizontally. This is weird because I specified it as below and that button is at the bottom of the screen. I'm not sure if the button lagged without bubbleTransition.

```
@IBOutlet var starButton: SpringButton! 
```

I create the segue using storyboard and just do:

```
override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
    if segue.identifier == "feedback" {
        let controller = segue.destinationViewController
        controller.transitioningDelegate = self
        controller.modalPresentationStyle = .Custom
    }
}
```

extension ViewController: UIViewControllerTransitioningDelegate {

```
func animationControllerForPresentedController(presented: UIViewController, presentingController presenting: UIViewController, sourceController source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
    transition.transitionMode = .Present
    transition.startingPoint = starButton.center
    transition.bubbleColor = UIColor(red: 245.0/255.0, green: 192.0/255.0, blue: 24.0/255.0, alpha: 1)
    return transition
}

func animationControllerForDismissedController(dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? {
    transition.transitionMode = .Dismiss
    transition.startingPoint = starButton.center
    transition.bubbleColor = UIColor(red: 245.0/255.0, green: 192.0/255.0, blue: 24.0/255.0, alpha: 1)
    return transition
}
```

}

**Comment by acegreen** [comment]
More info: Ended up having to calculate my starButton center by converting it first.

```
    let center = starButton.superview!.convertPoint(starButton.center, toView: self.view)
    transition.startingPoint = center
```

Now the bubble starts from the button. But there is still the first time lag.

**Comment by andreamazz** [comment]
It might be related to what your view is loading. Is there by any chance a mapkit object inside? I always notice a considerable lag the first time I load a map view.

**Comment by acegreen** [comment]
Yea I know what you mean. Had that before but my current segue is super simple and the VC is basically empty. Also the segue perform perfectly from the second time onwards. It's only the first time that it needs to think for a little. 

Also I got the whole idea from another project and in that project there is no lag the first time around. Also nowhere else is there a lag to find in my project except with that one button segue.

**Comment by andreamazz** [comment]
So if you remove the custom transition and use the basic modal, the lag disappears?

**Comment by acegreen** [comment]
Let me try that.

**Comment by acegreen** [comment]
device update to iOS 9.2 overnight so give me 5 minutes.

**Comment by acegreen** [comment]
@andreamazz i removed the transition by removing the code in PrepareForSegue but seems to also be a lag there the first time.

**Comment by andreamazz** [comment]
It shouldn't be related to the bubble then. Time to fire up the time profiler :grin:

**Comment by acegreen** [comment]
He issue is described here exactly as I'm seeing it:
http://stackoverflow.com/questions/28509252/performseguewithidentifier-very-slow-when-segue-is-modal

I perform the segue on storyboard so how according to the solution I would need to perform the segue programmatically and use dispatch. 

What do you think?

**Comment by andreamazz** [comment]
Might be worth a try, still it's pretty weird, I never encountered this issue.

**Comment by acegreen** [comment]
Doesn't work for me. I'm really surprised but this

**Comment by andreamazz** [comment]
Did you try to profile it?

**Comment by acegreen** [comment]
Never really played around with instruments or the other tools.

**Comment by andreamazz** [comment]
Always a good time to start :)  
It's pretty easy for basic forensics, pick the time profiler, start recording, trigger the segue and stop the recording. Then you can drill down in the list of calls to see which one takes the most time.

**Comment by acegreen** [comment]
Just took a shot at it. every time I hit record, my Xcode crashes with thread 1 error 

NVM Xcode session shouldn't be running

**Comment by andreamazz** [comment]
Awesome. Try launching instruments on its own and attach it to the running process on your phone.

**Comment by acegreen** [comment]
Ok did that and performed the segue and stopped. Now I see stuff I need translated

**Comment by andreamazz** [comment]
You should see the calls tack with the time it took for each stack. Drill down and check which func takes the most percentage.

**Comment by acegreen** [comment]
Ok I see 73% on the main thread

<img width="914" alt="screen shot 2015-12-09 at 10 45 22 am" src="https://cloud.githubusercontent.com/assets/10794609/11689900/f9fc9b68-9e61-11e5-90cd-e1d61ef17abe.png">

**Comment by andreamazz** [comment]
Keep opening the disclosure triangle until you reach a func call that you can recognize (either from UIKit or your code)

**Comment by acegreen** [comment]
Ah this is just not for me. I rather go at it the old fashion way. 

Do you happen to have 5 minutes to Skype?

I can't read through this at all

[Chronic_segue_analysis.trace.zip](https://github.com/andreamazz/BubbleTransition/files/57008/Chronic_segue_analysis.trace.zip)

**Comment by acegreen** [comment]
@andreamazz 

Ahh I knew it was going to be something super trivial. So as mentioned, I took some stuff from another project and forgot one small thing. In my VC I'm using a custom font that I didnt have as a system font or in my project bundle. 

So it seems its an Apple glitch because it resorts to System font but takes longer on first segue. Adding the fonts to the bundle, solves the issue.

**Comment by andreamazz** [comment]
Good to know :+1:
