### ISSUE TITLE
Setup with Carthage unable to build

### ISSUE THREAD

**Issue by planath** [andreamazz/BubbleTransition#21]
After adding your Framework in "Linked Frameworks and Libraries" I did following:
1. My run script includes
   /usr/local/bin/carthage copy-frameworks
2. Input files
   $(SRCROOT)/Carthage/Build/iOS/BubbleTransition.framework
3. This leaves me with following error:
   <img width="1072" alt="fatal error" src="https://cloud.githubusercontent.com/assets/6680829/15212960/43021a0c-1844-11e6-9bce-fc2e5d9d34d6.png">

Could it be related to the BubbleTransition.framework.dSYM file?
I found following Issue @carthage that could be useful: https://github.com/Carthage/Carthage/issues/507

**Comment by andreamazz** [comment]
It might be related to this: https://github.com/Carthage/Carthage/issues/1200

**Comment by andreamazz** [comment]
I've compiled the framework with the latest version of Carthage, and it seem to work now. Can you confirm it?

**Comment by planath** [comment]
It works perfectly now! Thank you very much for your research an d support. Great transition animation that you provide here 👍
