### ISSUE TITLE
Initializing

### ISSUE THREAD

**Issue by joshharington** [andreamazz/BubbleTransition#23]
How do I call the transition? I am creating buttons dynamically (in the code) so how do I attach it?

**Comment by andreamazz** [comment]
Hi @joshharington 
You can follow the readme and instead of implementing prepareForSegue, hooke the delegate and the transition style where you are instantiating your new controller:

``` swift
if let controller = /* your custom instantiation here */ {
  controller.transitioningDelegate = self
  controller.modalPresentationStyle = .Custom
  presentViewController(controller, animated: true, completion: nil)
}
```
