### ISSUE TITLE
Issue on Swift 3 and Xcode 8

### ISSUE THREAD

**Issue by BilalReffas** [andreamazz/BubbleTransition#26]
I updated the Source Code to Swift 3 but the problem is that the Bubble Transition not working anymore for me :( .

**Comment by the-freshlord** [comment]
I got it to work for me.

**Comment by BilalReffas** [comment]
Do you have example code ? The transition look's broken for me :/

**Comment by andreamazz** [comment]
I'll update it to swift 3 syntax in the next few days. I'll keep you posted

**Comment by the-freshlord** [comment]
@BilalReffas 
Also did you make sure that the pod target's `Use Legacy Swift Language Version` is set to no?

**Comment by BilalReffas** [comment]
I just use the file manually for testing so it works for me :) I will create a pull request thank you ! :)
