### ISSUE TITLE
When doing pod install, Swift 3 branch not being pulled.

### ISSUE THREAD

**Issue by the-freshlord** [andreamazz/BubbleTransition#29]
Hi, 

I noticed that the instructions for installing via Cocoapods isn't correct. When using `pod 'BubbleTransition', '~> 1.0.0'` in a podfile and then doing `pod install` in the terminal, it pulls an older version written in Swift 2.2. But if I do `pod 'BubbleTransition', :git => 'https://github.com/andreamazz/BubbleTransition.git'`, it pulls the master branch with has the lastest changes in Swift 3.0. Was wondering if it was setup like that on purpose?

**Comment by andreamazz** [comment]
The readme needs to be updated. Current pod version is 2.0.0
