### ISSUE TITLE
transition.startingPoint = BubbleBtn.center does not work

### ISSUE THREAD

**Issue by kiwo12345** [andreamazz/BubbleTransition#30]
I am using the button inside my Navbar like:

**Right bar button -> bar button items -> BubbleBtn**

But when I set: `transition.startingPoint = BubbleBtn.center` it will make the transition start form the very top right corner of my screen:

<img width="62" alt="dis" src="https://cloud.githubusercontent.com/assets/10579811/19193506/94b7bce6-8caa-11e6-9dd8-90a2a0647be4.png">

How can I make it start from the center of the button?

**Comment by andreamazz** [comment]
is it a UIButton or a UIBarButtonItem?

**Comment by kiwo12345** [comment]
@andreamazz UIButton :)

Right bar button -> bar button items -> **UIButton**

**Comment by andreamazz** [comment]
Ok, so it's inside a navigation bar. It's always tricky finding the right position for those buttons. Take a look at this [SO thread](http://stackoverflow.com/questions/14318368/uibarbuttonitem-how-can-i-find-its-frame)

**Comment by kiwo12345** [comment]
@andreamazz look like someone else was asking the same [thing](http://stackoverflow.com/questions/39931976/how-to-get-uibarbuttonitem-center-position) I will try to convert the answer into swift 3 and see if it works

**Comment by kiwo12345** [comment]
@andreamazz That didnt work : / I also added a image to my btn and tried to use the image center which did not work. Do you think I could wrap the btn inside a uiview and use the center of that view? running out of ideas now

**Comment by andreamazz** [comment]
It's always tricky getting the right position in the navigation bar. You can add some hardcoded offsets, it's not pretty, but it'll get the job done. 

I'm closing this issue if you don't mind, since it's not directly related to the library.

**Comment by kiwo12345** [comment]
@andreamazz this worked out perfect:

`transition.startingPoint = CGPoint(x: bubbleBtn.center.x, y: bubbleBtn.center.y + 20)`
