### ISSUE TITLE
what should be added if i have 2 button? 

### ISSUE THREAD

**Issue by ahikmatf** [andreamazz/BubbleTransition#31]
especially at this part `transition.startingPoint = transitionButton.center`

**Comment by andreamazz** [comment]
You just specify the button's center that is originating the transition.

**Comment by ahikmatf** [comment]
I mean, the `func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning? {}` will only have 1 `startingPoint` , 

then if I have 2 button, first button start from `button.center` position, and the second button from `view.center` . 

How do I do that?
