### ISSUE TITLE
I put `transmissionMode = .dismiss` in present mode and shows black. (Swift3, xCode8)

### ISSUE THREAD

**Issue by ahikmatf** [andreamazz/BubbleTransition#32]
what should I do if I want to have dismiss direction for presenting non modal controller?

**Comment by andreamazz** [comment]
I'm having a really hard time figuring out what you mean. My best guess is that this is related to #12, so make sure to check that out. Other than that, please provide a more descriptive issue, possibly with a sample demonstrating the issue.
