### ISSUE TITLE
How to use the bubble transition programmatically?

### ISSUE THREAD

**Issue by GaoleMeng** [andreamazz/BubbleTransition#41]
In the demo, the action is directly binding to the storyboard, but when I try to self.present new viewcontroller, the bubble transition won't work, what should I do?

Thanks

**Comment by GaoleMeng** [comment]
Solved!

**Comment by birbay** [comment]
> Solved!

how did you solve it?

**Comment by birbay** [comment]
I Solved like this

        if let controller = segue.destination as? LoginViewController {
            controller.transitioningDelegate = self
            controller.modalPresentationStyle = .custom
            present(controller, animated: true, completion: nil)
        }
