### ISSUE TITLE
Swipe down to dismiss

### ISSUE THREAD

**Issue by ryandailey100** [andreamazz/BubbleTransition#46]
Is there a way to swipe down to dismiss the ModalViewController? If so, how can this be done? Can that be added in a next update? Please let me know, thanks!

**Comment by andreamazz** [comment]
No, there is no way currently, and I'm not planning on adding this feature at the moment. It would be a great addition though. if anyone wants to pitch in, PRs are always welcome.

**Comment by andreamazz** [comment]
I ended up implementing it myself. Checkout commit 181f663
I'm going to document it better tomorrow, but for now you can check out the sample project.

**Comment by ryandailey100** [comment]
Works great! Appreciate the implementation. Thanks 👍

**Comment by andreamazz** [comment]
Great. I've added the swipe direction and improved the docs. Released version `3.1.0`.  
👍
