### ISSUE TITLE
Animation Controller for Dismissed Not work in iOS 9.3 & iOS 12

### ISSUE THREAD

**Issue by bauloc** [andreamazz/BubbleTransition#49]
Thanks to the author for the great library, very easy to use, however
I can not run the dismissal effect on ios 9.3 and ios 12. Please check again.
Thank you.

**Comment by andreamazz** [comment]
Great. The funny thing is that the view hierarchy inspector looks fine:
![screenshot 2018-09-26 at 10 18 34](https://user-images.githubusercontent.com/570797/46066811-a0ecad80-c175-11e8-9b51-15c6846b7f18.png)

**Comment by andreamazz** [comment]
I'll toss this to an iOS issue, filed radar 44790012.

**Comment by andreamazz** [comment]
Another reference to the issue: https://forums.developer.apple.com/thread/108568

**Comment by sushilskycap** [comment]
Same issue. It just stuck at the presentedViewController. if I press home button and open app from app icon, it show the presentingViewController.

**Comment by andreamazz** [comment]
It's an iOS issue, open or dup a radar, no point in +1ing this issue

**Comment by andreamazz** [comment]
Check out the updates in c283745 to implement the fix.
