### ISSUE TITLE
Objective-C instructions 

### ISSUE THREAD

**Issue by magnett** [andreamazz/BubbleTransition#5]
Hi!
Your work is amazing however, i am not into Swift.
I imported your file, created the necessary bridging header and everything compiles, however i don't know how to "activate" the transition and use the delegates. Could you please provide an objective-c example?
Thanks in advance.

**Comment by andreamazz** [comment]
Hi @magnett 
Yeah, something's off when importing the pod in an Objective-C project. The enum with the transition mode is not translated in the header file. Pretty weird, I'll have to investigate.

**Comment by magnett** [comment]
I also had that problem so i didn't use cocoapods, i just imported the BubbleTransition.swift

**Comment by andreamazz** [comment]
And you can access the `transitionMode` property and the `BubbleTransitionMode` enum?

**Comment by magnett** [comment]
I don't know how to that (even if possible) !

**Comment by andreamazz** [comment]
Ok, I forgot to annotate the enum with `@objc`. 
Pull the latest version of the code. Here's a gist with the Objective-C implementation:
https://gist.github.com/andreamazz/9b0d6c7db065555ec0d7

**Comment by andreamazz** [comment]
This might help too:
http://d.pr/f/1ilaz
