### ISSUE TITLE
Cannot use BubbleInteractiveTransition

### ISSUE THREAD

**Issue by lyx0124** [andreamazz/BubbleTransition#56]
Thanks for this library! But after I added it to my project using cocoapods, I can't use BubbleInteractiveTransition class. However, I can use BubbleTransition. And I checked "BubbleTransition.swift" file, it seems that there is no BubbleInteractiveTransition class at all. I don't why this happens.

**Comment by andreamazz** [comment]
It's [here](https://github.com/andreamazz/BubbleTransition/blob/master/Source/BubbleTransition.swift#L115)

Are you using objective-C?

**Comment by lyx0124** [comment]
I'm using swift.
There indeed is a BubbleInteractiveTransition class in github file. However the file I installed to my project through cocoapods doesn't. It's very strange. The "BubbleTransition.swift" file is different to the one on github.

**Comment by andreamazz** [comment]
I just tested it out, it pulls the correct version (3.2.0)  
Maybe you are pulling an older version, check the `cocoapods install` output, it should read:
```
Installing BubbleTransition (3.2.0)
```

**Comment by lyx0124** [comment]
It seems the README file still says pod 'BubbleTransition', '~> 3.0.0'. After changing my pod to 3.2.0, everything worked out just fine. Thanks for your help!
