### ISSUE TITLE
Button clicks or tableview cell selection not working

### ISSUE THREAD

**Issue by hardikamal** [andreamazz/BubbleTransition#59]
Hi, 
First of all thanks for the awesome library
I have added a button and tableview in the presented view. But the button clicks or tableview cell selection are not working.

**Comment by andreamazz** [comment]
Hey @hardikamal 
I'll need a bit more info to troubleshoot this. A sample project showing the issue would be also great.

**Comment by hardikamal** [comment]
Issue on my side. Had turned off the user interaction by mistake.

Thanks
