### ISSUE TITLE
about `UIStatusBarStyle`

### ISSUE THREAD

**Issue by birdmichael** [andreamazz/BubbleTransition#61]
Because  newVC.modalPresentationStyle = .custom
so, Is not working
```
override var preferredStatusBarStyle: UIStatusBarStyle {
        if #available(iOS 13.0, *) {
            return .darkContent
        } else {
            return .default
        }
    }
```

If oldVC and NewVC have different status bar styles, What should I do?

**Comment by birdmichael** [comment]
Thank you for your excellent work, I have achieved a relative solution.
```
.modalPresentationCapturesStatusBarAppearance = true
```
I think we can add this code to the demo.

**Comment by andreamazz** [comment]
Hi @birdmichael 
Good call, I've added that flag to the demo and the documentation. 
Thanks
