### ISSUE TITLE
CARTHAGE SUPPORT.

### ISSUE THREAD

**Issue by istx25** [andreamazz/BubbleTransition#7]
https://github.com/andreamazz/BubbleTransition/pull/8

You may have to update your pods.

**Comment by jadsonlourenco** [comment]
I don't want open new issue for this question, maybe can reopen the current. I get this error:

```
xcodebuild: error: Scheme Pods-DemoTests-BubbleTransition is not currently configured for the build action.
```

**Comment by andreamazz** [comment]
Hi @jadsonlourenco 
Let me check this right away

**Comment by andreamazz** [comment]
Wait, you get this error doing what? A plain `carthage update` on your project?

edit: ok, I get the same

**Comment by andreamazz** [comment]
Ok, I'm confused. `xcodebuild -project BubbleTransition.xcodeproj -scheme BubbleTransition` runs fine, `carthage build --no-skip-current` doesn't. Any idea?

**Comment by andreamazz** [comment]
Never mind, solved it, checkout the latest version. I'll include the prebuilt archive in the [next release](https://github.com/andreamazz/BubbleTransition/releases/tag/1.0.2)

**Comment by jadsonlourenco** [comment]
Hey @andreamazz now works fine thank you!

**Comment by istx25** [comment]
:+1:
