### ISSUE TITLE
Orientations

### ISSUE THREAD

**Issue by JDandini** [andreamazz/BubbleTransition#9]
#### Problem

I use your beautiful control but when you make a presentation to a view controller with autorotate the rotation misses 

```
- (NSUInteger)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskLandscape;
}

-(BOOL)shouldAutorotate {
    return YES;
}
```

Can you give me a idea to get this done please?

**Comment by andreamazz** [comment]
Sure, the animation was a little wonky since the position was not reset properly upon rotation. I fixed it and added rotation to the demo app in this repo. Let me know if that works for you.
